name: oliverdavies-uk
type: drupal
language: php

project_root: /var/www/html

web:
  type: apache

database:
  type: mariadb
  version: 10
  extra_databases: []

php:
  version: 8.2-apache
  phpcs:
    paths:
      - web/modules/custom
    standards:
      - Drupal
  phpstan:
    level: 1
    paths:
      - web/modules/custom

drupal:
  docroot: web

docker-compose:
  services:
    - database
    - php

dockerfile:
  stages:
    build:
      extra_directories:
        - tools
      commands:
        - composer validate --strict
        - composer install --quiet --no-progress

git:
  ignore:
    - '!/phpstan.neon'
    - '!/tests/Architecture/**'
    - .devenv*
    - devenv.local.nix
    - .direnv
    - .pre-commit-config.yaml
    - html/

experimental:
  createGitHubActionsConfiguration: true
