<?php

/**
 * Implements hook_preprocess_image_style().
 *
 * @param array{ style_name: string, image: array{ "#attributes": array{ class: string[] }}} $variables
 */
function opdavies_preprocess_image_style(array &$variables): void {
  if ($variables['style_name'] === 'testimonial' || $variables['style_name'] === 'thumbnail') {
    $variables['image']['#attributes']['class'] = 'size-16 rounded-full ring-[3px] ring-blue-primary dark:ring-white';
  }
}
